name: 🐛 Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of RazorpayKit are you using?
      placeholder: "e.g., v1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize client with '...'
        2. Call method '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a code sample to demonstrate the issue
      render: swift
      placeholder: |
        let client = RazorpayClient(...)
        try await client.order.create(...)

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: swift
    attributes:
      label: Swift Version
      options:
        - Swift 5.8
        - Swift 5.9
        - Swift 6.0
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options:
        - iOS
        - macOS
        - tvOS
        - watchOS
    validations:
      required: true